<template>
  <div class="loader">
    <p class="loader_item">🍽️</p>
  </div>
</template>

<script>
export default {
  name: 'AppLoader',
};
</script>

<style lang="scss">
.loader {
  width: 100%;
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;

  .loader_item {
    width: 150px;
    height: 150px;
    border: 5px solid black;
    border-radius: 100px;
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 70px;
    -webkit-animation: rotate-center 0.7s ease-in-out infinite both;
    animation: rotate-center 0.7s ease-in-out infinite both;
  }

  /* ----------------------------------------------
 * Generated by Animista on 2021-3-29 16:3:43
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation rotate-center
 * ----------------------------------------
 */
  @-webkit-keyframes rotate-center {
    0% {
      -webkit-transform: rotate(0);
      transform: rotate(0);
    }
    100% {
      -webkit-transform: rotate(360deg);
      transform: rotate(360deg);
    }
  }
  @keyframes rotate-center {
    0% {
      -webkit-transform: rotate(0);
      transform: rotate(0);
    }
    100% {
      -webkit-transform: rotate(360deg);
      transform: rotate(360deg);
    }
  }
}
</style>
